=== apache-red/HW_24_Xml_parser_SAX_StAX_DOM/resources/FamilySchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/FamilySchema"
        xmlns:tns="http://www.example.org/FamilySchema"
        elementFormDefault="qualified">

    <xs:element name="Families">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="family" maxOccurs="unbounded" minOccurs="1" type="tns:family_type" />
        </xs:sequence>
    </xs:complexType>
</xs:element>


    <xs:complexType name="family_type">
        <xs:sequence>
            <xs:element name="mother" maxOccurs="unbounded" minOccurs="1" type="tns:mother_type" />
            <xs:element name="father" maxOccurs="unbounded" minOccurs="1" type="tns:father_type" />
            <xs:element name="children" maxOccurs="unbounded" minOccurs="1" type="tns:children_type" />
        </xs:sequence>
        <xs:attribute name="adress" type="xs:string"/>
    </xs:complexType>


    <xs:complexType name="mother_type">
        <xs:sequence>
            <xs:element name="maidenname" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="name" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="surname" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="age" maxOccurs="unbounded" minOccurs="1" type="xs:int" />
            <xs:element name="gender" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="hobby" maxOccurs="unbounded" minOccurs="1" type="tns:hobby_type" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hobby_type">
        <xs:sequence>
            <xs:element name="title" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="times-per-week" maxOccurs="unbounded" minOccurs="1" type="xs:int" />
            <xs:element name="schedule" maxOccurs="unbounded" minOccurs="1" type="tns:schedule_type" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="schedule_type">
        <xs:sequence>
            <xs:element name="day" maxOccurs="unbounded" minOccurs="1" type="tns:day_type" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="day_type">
        <xs:sequence>
            <xs:element name="day_name" id="gDay" />
            <xs:element name="time"  type="xs:time" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="father_type">
        <xs:sequence>
            <xs:element name="name" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="surname" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="age" maxOccurs="unbounded" minOccurs="1" type="xs:int" />
            <xs:element name="gender" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="children_type">
        <xs:sequence>
            <xs:element name="child" maxOccurs="unbounded" minOccurs="1" type="tns:child_type" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="child_type">
        <xs:sequence>
            <xs:element name="name" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="surname" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
            <xs:element name="age" maxOccurs="unbounded" minOccurs="1" type="xs:int" />
            <xs:element name="gender" maxOccurs="unbounded" minOccurs="1" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== apache-red/HW_24_Xml_parser_SAX_StAX_DOM/resources/Families.xml
<?xml version="1.0" encoding="UTF-8"?>

<Families xmlns="http://www.example.org/FamilySchema"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.example.org/FamilySchema FamilySchema.xsd">
    <family adress="Belarus, Minsk, Engelsa №234">
        <mother>
            <maidenname>Ivanova</maidenname>
            <name>Kate</name>
            <surname>Petpova</surname>
            <age>31</age>
            <gender>female</gender>
            <hobby>
                <title>Dancing</title>
                <times-per-week>2</times-per-week>
                <schedule>
                    <day>
                        <day_name>monday</day_name>
                        <time>18:00:00</time>
                    </day>
                    <day>
                        <day_name>friday</day_name>
                        <time>18:00:00</time>
                    </day>
                </schedule>
            </hobby>
        </mother>

        <father>
            <name>Igor</name>
            <surname>Petpov</surname>
            <age>32</age>
            <gender>male</gender>
        </father>

        <children>

            <child>
                <name>Oleg</name>
                <surname>Petpov</surname>
                <age>5</age>
                <gender>male</gender>
            </child>

            <child>
                <name>Masha</name>
                <surname>Petpova</surname>
                <age>6</age>
                <gender>female</gender>
            </child>

        </children>

    </family>

    <family adress="Belarus, Gomel, Kalinina №23">
        <mother>
            <maidenname>Sidorova</maidenname>
            <name>Tanya</name>
            <surname>Peshkina</surname>
            <age>47</age>
            <gender>female</gender>
            <hobby>
                <title>Cooking</title>
                <times-per-week>2</times-per-week>
                <schedule>
                    <day>
                        <day_name>wednesday</day_name>
                        <time>19:30:00</time>
                    </day>
                    <day>
                        <day_name>saturday</day_name>
                        <time>11:00:00</time>
                    </day>
                </schedule>
            </hobby>
        </mother>

        <father>
            <name>Vasya</name>
            <surname>Sidorov</surname>
            <age>52</age>
            <gender>male</gender>
        </father>

        <children>

            <child>
                <name>Nastya</name>
                <surname>Sidorova</surname>
                <age>17</age>
                <gender>female</gender>
            </child>

        </children>


    </family>


</Families>
